import javax.swing.*; 
import java.awt.*; 
/**
 * Write a description of class GuiWindow here.
 *
 * @author (your name)
 * @version (a version number or a date)
 */
public class Greece
{
   // Page 47 of fundamentals of JAVA 
    public static void main(String[] args) {
        JFrame  theGui = new JFrame(); 
        theGui.setTitle("Fifth GUI Program"); 
        theGui.setSize(300,200); 
        theGui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel panel1 = new JPanel();
        panel1.setBackground(Color.blue);
        JPanel panel2 = new JPanel();
        panel2.setBackground(Color.blue);
        JPanel panel3 = new JPanel();
        panel3.setBackground(Color.white);
        JPanel panel4 = new JPanel();
        panel4.setBackground(Color.blue);
        JPanel panel5 = new JPanel();
        panel5.setBackground(Color.blue);
        JPanel panel6 = new JPanel();
        panel6.setBackground(Color.blue);
        JPanel panel7 = new JPanel();
        panel7.setBackground(Color.blue);
        JPanel panel8 = new JPanel();
        panel8.setBackground(Color.blue);
        JPanel panel9 = new JPanel();
        panel9.setBackground(Color.blue);
        JPanel panel10 = new JPanel();
        panel10.setBackground(Color.blue);
        JPanel panel11 = new JPanel();
        panel11.setBackground(Color.blue);
        JPanel panel12 = new JPanel();
        panel12.setBackground(Color.white);
        JPanel panel13 = new JPanel();
        panel13.setBackground(Color.blue);
        JPanel panel14 = new JPanel();
        panel14.setBackground(Color.blue);
        JPanel panel15 = new JPanel();
        panel15.setBackground(Color.white);
        JPanel panel16 = new JPanel();
        panel16.setBackground(Color.white);
        JPanel panel17 = new JPanel();
        panel17.setBackground(Color.white);
        JPanel panel18 = new JPanel();
        panel18.setBackground(Color.white);
        JPanel panel19 = new JPanel();
        panel19.setBackground(Color.white);
        JPanel panel20 = new JPanel();
        panel20.setBackground(Color.white);
        JPanel panel21 = new JPanel();
        panel21.setBackground(Color.white);
        JPanel panel22 = new JPanel();
        panel22.setBackground(Color.white);
        JPanel panel23 = new JPanel();
        panel23.setBackground(Color.white);
        JPanel panel24 = new JPanel();
        panel24.setBackground(Color.blue);
        JPanel panel25 = new JPanel();
        panel25.setBackground(Color.blue);
        JPanel panel26 = new JPanel();
        panel26.setBackground(Color.blue);
        JPanel panel27 = new JPanel();
        panel27.setBackground(Color.blue);
        JPanel panel28 = new JPanel();
        panel28.setBackground(Color.blue);
        JPanel panel29 = new JPanel();
        panel29.setBackground(Color.blue);
        JPanel panel30 = new JPanel();
        panel30.setBackground(Color.white);
        JPanel panel31 = new JPanel();
        panel31.setBackground(Color.blue);
        JPanel panel32 = new JPanel();
        panel32.setBackground(Color.blue);
        JPanel panel33 = new JPanel();
        panel33.setBackground(Color.white);
        JPanel panel34 = new JPanel();
        panel34.setBackground(Color.white);
        JPanel panel35 = new JPanel();
        panel35.setBackground(Color.white);
        JPanel panel36 = new JPanel();
        panel36.setBackground(Color.white);
        JPanel panel37 = new JPanel();
        panel37.setBackground(Color.blue);
        JPanel panel38 = new JPanel();
        panel38.setBackground(Color.blue);
        JPanel panel39 = new JPanel();
        panel39.setBackground(Color.white);
        JPanel panel40 = new JPanel();
        panel40.setBackground(Color.blue);
        JPanel panel41 = new JPanel();
        panel41.setBackground(Color.blue);
        JPanel panel42 = new JPanel();
        panel42.setBackground(Color.blue);
        JPanel panel43 = new JPanel();
        panel43.setBackground(Color.blue);
        JPanel panel44 = new JPanel();
        panel44.setBackground(Color.blue);
        JPanel panel45 = new JPanel();
        panel45.setBackground(Color.blue);
        JPanel panel46 = new JPanel();
        panel46.setBackground(Color.white);
        JPanel panel47 = new JPanel();
        panel47.setBackground(Color.white);
        JPanel panel48 = new JPanel();
        panel48.setBackground(Color.white);
        JPanel panel49 = new JPanel();
        panel49.setBackground(Color.white);
        JPanel panel50 = new JPanel();
        panel50.setBackground(Color.white);
        JPanel panel51 = new JPanel();
        panel51.setBackground(Color.white);
        JPanel panel52 = new JPanel();
        panel52.setBackground(Color.white);
        JPanel panel53 = new JPanel();
        panel53.setBackground(Color.white);
        JPanel panel54 = new JPanel();
        panel54.setBackground(Color.white);
        JPanel panel55 = new JPanel();
        panel55.setBackground(Color.blue);
        JPanel panel56 = new JPanel();
        panel56.setBackground(Color.blue);
        JPanel panel57 = new JPanel();
        panel57.setBackground(Color.blue);
        JPanel panel58 = new JPanel();
        panel58.setBackground(Color.blue);
        JPanel panel59 = new JPanel();
        panel59.setBackground(Color.blue);
        JPanel panel60 = new JPanel();
        panel60.setBackground(Color.blue);
        JPanel panel61 = new JPanel();
        panel61.setBackground(Color.blue);
        JPanel panel62 = new JPanel();
        panel62.setBackground(Color.blue);
        JPanel panel63 = new JPanel();
        panel63.setBackground(Color.blue);
        JPanel panel64 = new JPanel();
        panel64.setBackground(Color.white);
        JPanel panel65 = new JPanel();
        panel65.setBackground(Color.white);
        JPanel panel66 = new JPanel();
        panel66.setBackground(Color.white);
        JPanel panel67 = new JPanel();
        panel67.setBackground(Color.white);
        JPanel panel68 = new JPanel();
        panel68.setBackground(Color.white);
        JPanel panel69 = new JPanel();
        panel69.setBackground(Color.white);
        JPanel panel70 = new JPanel();
        panel70.setBackground(Color.white);
        JPanel panel71 = new JPanel();
        panel71.setBackground(Color.white);
        JPanel panel72 = new JPanel();
        panel72.setBackground(Color.white);
        JPanel panel73 = new JPanel();
        panel73.setBackground(Color.blue);
        JPanel panel74 = new JPanel();
        panel74.setBackground(Color.blue);
        JPanel panel75 = new JPanel();
        panel75.setBackground(Color.blue);
        JPanel panel76 = new JPanel();
        panel76.setBackground(Color.blue);
        JPanel panel77 = new JPanel();
        panel77.setBackground(Color.blue);
        JPanel panel78 = new JPanel();
        panel78.setBackground(Color.blue);
        JPanel panel79 = new JPanel();
        panel79.setBackground(Color.blue);
        JPanel panel80 = new JPanel();
        panel80.setBackground(Color.blue);
        JPanel panel81 = new JPanel();
        panel81.setBackground(Color.blue);



        Container pane = theGui.getContentPane(); 
        pane.setLayout(new GridLayout(9,9)); 
        pane.add(panel1);
        pane.add(panel2);
        pane.add(panel3);
        pane.add(panel4);
        pane.add(panel5);
        pane.add(panel6);
        pane.add(panel7);
        pane.add(panel8);
        pane.add(panel9);
        pane.add(panel10);
        pane.add(panel11);
        pane.add(panel12);
        pane.add(panel13);
        pane.add(panel14);
        pane.add(panel15);
        pane.add(panel16);
        pane.add(panel17);
        pane.add(panel18);
        pane.add(panel19);
        pane.add(panel20);
        pane.add(panel21);
        pane.add(panel22);
        pane.add(panel23);
        pane.add(panel24);
        pane.add(panel25);
        pane.add(panel26);
        pane.add(panel27);
        pane.add(panel28);
        pane.add(panel29);
        pane.add(panel30);
        pane.add(panel31);
        pane.add(panel32);
        pane.add(panel33);
        pane.add(panel34);
        pane.add(panel35);
        pane.add(panel36);
        pane.add(panel37);
        pane.add(panel38);
        pane.add(panel39);
        pane.add(panel40);
        pane.add(panel41);
        pane.add(panel42);
        pane.add(panel43);
        pane.add(panel44);
        pane.add(panel45);
        pane.add(panel46);
        pane.add(panel47);
        pane.add(panel48);
        pane.add(panel49);
        pane.add(panel50);
        pane.add(panel51);
        pane.add(panel52);
        pane.add(panel53);
        pane.add(panel54);
        pane.add(panel55);
        pane.add(panel56);
        pane.add(panel57);
        pane.add(panel58);
        pane.add(panel59);
        pane.add(panel60);
        pane.add(panel61);
        pane.add(panel62);
        pane.add(panel63);
        pane.add(panel64);
        pane.add(panel65);
        pane.add(panel66);
        pane.add(panel67);
        pane.add(panel68);
        pane.add(panel69);
        pane.add(panel70);
        pane.add(panel71);
        pane.add(panel72);
        pane.add(panel73);
        pane.add(panel74);
        pane.add(panel75);
        pane.add(panel76);
        pane.add(panel77);
        pane.add(panel78);
        pane.add(panel79);
        pane.add(panel80);
        pane.add(panel81);

       
        theGui.setVisible(true); 
    }
}